### ISSUE TITLE
ObjectDisposedException

### ISSUE THREAD

**Issue by marknelissen** [siniypin/pjsip4net#40]
Hi, 

When closing the application that is using pjsip4net, I get the following error:

````
System.ObjectDisposedException was unhandled
Message: An unhandled exception of type 'System.ObjectDisposedException' occurred in pjsip4net.dll
Additional information: Cannot access a disposed object.

Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'account'.
   at pjsip4net.Accounts.RegistrationSession.get_Account()
   at pjsip4net.Accounts.RegisteredAccountState.StateChanged()
   at pjsip4net.Core.Utils.StateMachine.HandleStateChanged()
   at pjsip4net.Accounts.DefaultAccountManager.OnRegistrationState(RegistrationStateChanged e)
   at pjsip4net.Accounts.DefaultAccountManager.<EndInit>b__9(RegistrationStateChanged e)
   at pjsip4net.Core.DelegatingConsumer`1.Consume(T message)
   at Magnum.Pipeline.Segments.MessageConsumerSegment`1.<>c__DisplayClassd`1.<Accept>b__c(T x)
   at Magnum.Pipeline.Segments.PipeSegment.<>c__DisplayClass1`1.<Send>b__0(MessageConsumer`1 consumer)
   at Magnum.Extensions.ExtensionsToEnumerable.Each[T](IEnumerable`1 collection, Action`1 callback)
   at Magnum.Pipeline.Segments.PipeSegment.Send[T](T message)
   at pjsip4net.Core.EventsProvider.Publish[T](T event)
   at pjsip.Interop.ApiProviders.BasicApiProvider_1_4.The program '[2480] ***.exe' has exited with code 0 (0x0).
OnRegState(Int32 accId)
   at pjsip.Interop.PJSUA_DLL.Basic.pjsua_destroy()
   at pjsip.Interop.ApiProviders.BasicApiProvider_1_4.Destroy()
   at pjsip4net.DefaultSipUserAgent.CleanUp()
   at pjsip4net.Core.Resource.Finalize()
```
I've tried not explicitly disposing any object, and manually disposing the SipUserAgent. What do I need to do to avoid this?

**Comment by siniypin** [comment]
Hi, 
do you setup accounts that register with remote registrar server? Can you submit an example to reproduce an error?

**Comment by siniypin** [comment]
Do you call `ISipUserAgent.Destroy()` method explicitly as in an example console app (https://github.com/siniypin/pjsip4net/blob/master/Tests/Integration/pjsip4net.Console/Program.cs#L56)?

**Comment by marknelissen** [comment]
Hi,

My bad, I forgot some Dispose calls along the object reference chain. When actually calling the ISipUserAgent.Dispose() method (not just having it in an uncalled piece of code ;) ), I don't get the error.

Thank you for your quick responses.
