### ISSUE TITLE
Download and running Build.bat

### ISSUE THREAD

**Issue by toLucky81** [siniypin/pjsip4net#63]
Hi everyone

I just downloaded and unzipped pjsip4net. Opened it in VS 2015 and then i got the first error...
Source file C:\.... \pjsip4.Core\SolutionVersion.cs
Google Google - ok, i needed to run the Build.bat first... So I ran it... got an error, so I ran it again as Administrator - Still got the error - See the image

![image](https://cloud.githubusercontent.com/assets/23236098/19964258/11933b0c-a1c1-11e6-955e-54db8f15c370.png)

How to overcome this???

Dennis Jensen

**Comment by toLucky81** [comment]
The entire text in console is:


Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'NAnt.Console.ConsoleStub' threw an exception. ---> System.Security.SecurityEx
ception: Request for the permission of type 'System.Security.Permissions.FileIOP
ermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5619
34e089' failed.
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMa
rk& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessSecurityEngine.Check(CodeAccessPermission cap, S
tackCrawlMark& stackMark)
   at System.Security.CodeAccessPermission.Demand()
   at System.AppDomainSetup.VerifyDir(String dir, Boolean normalize)
   at System.AppDomain.get_BaseDirectory()
   at log4net.Config.XmlConfiguratorAttribute.Configure(Assembly sourceAssembly,
 ILoggerRepository targetRepository)
   at log4net.Core.DefaultRepositorySelector.ConfigureRepository(Assembly assemb
ly, ILoggerRepository repository)
   at log4net.Core.DefaultRepositorySelector.CreateRepository(Assembly repositor
yAssembly, Type repositoryType, String repositoryName, Boolean readAssemblyAttri
butes)
   at log4net.Core.DefaultRepositorySelector.CreateRepository(Assembly repositor
yAssembly, Type repositoryType)
   at log4net.Core.DefaultRepositorySelector.GetRepository(Assembly repositoryAs
sembly)
   at log4net.Core.LoggerManager.GetLogger(Assembly repositoryAssembly, String n
ame)
   at log4net.LogManager.GetLogger(Assembly repositoryAssembly, String name)
   at log4net.LogManager.GetLogger(Type type)
   at NAnt.Console.ConsoleStub..cctor()
   --- End of inner exception stack trace ---
   at NAnt.Console.ConsoleStub.Main(String[] args)

**Comment by siniypin** [comment]
Try to "unblock" that zip file after download and then unpack it, or unblock every unpacked .dll and .exe file.

https://sourceforge.net/p/nant/mailman/message/27446299/

**Comment by siniypin** [comment]
Use https://github.com/siniypin/pjsip4net/#installation better, if you do not plan to make any changes to the source code, otherwise fork the repo.

**Comment by siniypin** [comment]
btw, did you read readme first? https://github.com/siniypin/pjsip4net#examples

**Comment by toLucky81** [comment]
Unblock did the trick i think... - Well the Built.bat ran and closed without any error at least. 

THANKS

**Comment by toLucky81** [comment]
Minor detail...

The SolutionVersion.cs is put in the ..\pjsip4net-master\
NOT in the  ..\pjsip4net-master\pjsip4net.Core\ where VS is looking for it

I searched the build.log and found where it was put, copied it and now VS is building - at least :)

**Comment by toLucky81** [comment]
There is more issues.

I ran the Tests\Integration\pjsip4net.Console project and when it finally showed something on the console, it ran into this "


![image](https://cloud.githubusercontent.com/assets/23236098/19965404/1b1380dc-a1c7-11e6-867e-078a0287c32c.png)


Any clues?
